

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
